### ISSUE TITLE
Viewer Shutdown

### ISSUE THREAD

**Issue by VileOar** [dgomes/iia-ia-bomberman#2]
```DEBUG:Map:Add Exit
DEBUG:Map:Add Exit
DEBUG:Map:Add Detonator
Traceback (most recent call last):
  File "viewer.py", line 522, in <module>
    asyncio.gather(messages_handler(ws_path, q), main_loop(q))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "viewer.py", line 332, in main_loop
    await main_game()
  File "viewer.py", line 405, in main_game
    p = Powerups(pos=pos, name=name)
  File "viewer.py", line 284, in __init__
    self.sprite = (SPRITES, (0, 0), (*POWERUPS[self.type], *scale((1, 1))))
KeyError: 'Detonator'
```

**Comment by dgomes** [comment]
Tks
